# import all necessary components
import smtplib
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
import  datetime

port = 2525
smtp_server = "smtp.mailtrap.io"
login = "" # paste your login generated by Mailtrap
password = "" # paste your password generated by Mailtrap

sender_email = "mailtrap@example.com"
receiver_email = "researchdatacollection@gmail.com"
message = MIMEMultipart("alternative")
message["Subject"] = "CID image test"
message["From"] = sender_email
message["To"] = receiver_email
html = """\
<html>
 <body>
   <img src="cid:Mailtrapimage">
 </body>
</html>
"""

part = MIMEText(html, "html")
message.attach(part)

# We assume that the image file is in the same directory that you run your Python script from
fp = open('one.jpg', 'rb')
image = MIMEImage(fp.read())
fp.close()
image.add_header('Content-ID', '<Mailtrapimage>')
message.attach(image)

# send your email
begin_time=datetime.datetime.now()
with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
   server.login(login, password)
   server.sendmail(
       sender_email, receiver_email, message.as_string()
   )
print('Sent')
timetaken = datetime.datetime.now()-begin_time
print(f"it took {timetaken}")


